#---------------------------------------------------------------------------------------------------------
#packages
library("ows4R")
library("sp")
library("shiny")
library("DT")
library("readr")
library("stringr")
library("shinyWidgets")
library("shinycssloaders")
library("jsonlite")
library("leaflet")
library("shinydashboard")
library("ggplot2")
library("plotly")
library("plyr")
library("shinyjs")
library("shinybusy")
library("paletteer")
library("data.table")
library("sf")

#load module functions
source("https://raw.githubusercontent.com/eblondel/OpenFairViewer/master/src/resources/shinyModule/QueryInfo.R")
#source("D:/FAO-BLUECLOUD_04052020_11082020/02-R/04-Github/OpenFairViewer/src/resources/shinyModule/QueryInfo.R")
source("Registers.R")
source("modules/Rename.R")
source("modules/Summary.R")
source("modules/Data.R")
#source("modules/SubsetRegion.R")
source("modules/Country.R")

#source("ui.R")
#source("server.R")

